skillMetadata:
  sections:
    - name: Calendar Location
      fields:
        - type: label
          label: By default, the calendar skill defaults to saving your calendar on your device. However, if you wish to connect to a CalDAV server, you can select the setting here then fill out the information below. You can also <a href='http://bit.ly/mycroft-calendar-ics'>learn more about ics files.</a>
        - name: server_type
          type: select
          label: Calendar Location
          value: "local"
          options: Locally on the device|local;CalDAV server|CalDAV
    - name: CalDAV Login
      fields:
        - type: label
          label: <b>If you selected CalDAV Server</b> above, fill out the form here, to connect Mycroft to your CalDAV account. If you wish not to enter this information in here, you can <a href='https://bit.ly/mycroft-calendar-local'>configure the skill on your device</a>
        - name: caldav.username
          type: text
          label: Username
          value: ""
        - name: caldav.password
          type: password
          label: Password
          value: ""
        - name: caldav.server_address
          type: text
          label: CalDAV server address (e.g. https://my-nextcloud.com/remote.php/dav/calendars/my-name/)
          value: ""
        - name: caldav.calendar_name
          type: text
          label: Calendar name
          value: ""
